"""
Predefined difficulty buckets for Clembench games.
Each key maps to a list of (game_name, experiment_name) pairs.
"""

DIFFICULTY_BUCKETS = {
    "easy": [
        ("adventuregame", "home_deliver_three_basic_easy"),
        ("adventuregame", "home_deliver_three_basic_easy_invlimittwo"),
        ("codenames", "easy"),
        ("codenames", "none"),
        ("codenames", "unambiguous"),
        ("codenames", "concrete"),
        ("guesswhat", "Level_1"),
        ("guesswhat", "Abs_Level_1"),
        ("imagegame", "compact_grids"),
        ("matchit_ascii", "same_grid"),
        ("reference_game", "letter_grids"),
        ("reference_game", "number_grids"),
        ("reference_game", "line_grids_rows"),
        ("taboo", "high_en"),
        ("textmapworld", "small"),
        ("textmap_graphreasoning", "small"),
        ("textmap_specificroom", "on"),
        ("wordle", "high_frequency_words_no_clue_no_critic"),
    ],
    "medium": [
        ("adventuregame", "home_deliver_three_planning_easy"),
        ("adventuregame", "home_deliver_three_planning_easy_invlimittwo"),
        ("codenames", "high"),
        ("codenames", "difficult"),
        ("codenames", "low"),
        ("codenames", "ambiguous"),
        ("codenames", "abstract"),
        ("guesswhat", "Level_2"),
        ("guesswhat", "Abs_Level_2"),
        ("imagegame", "random_grids"),
        ("matchit_ascii", "similar_grid_1"),
        ("matchit_ascii", "similar_grid_2"),
        ("privateshared", "travel-booking"),
        ("privateshared", "job-interview"),
        ("privateshared", "restaurant"),
        ("privateshared", "things-places"),
        ("privateshared", "letter-number"),
        ("reference_game", "line_grids_columns"),
        ("taboo", "medium_en"),
        ("textmapworld", "medium"),
        ("textmap_graphreasoning", "medium"),
        ("textmap_specificroom", "close"),
        ("wordle", "medium_frequency_words_no_clue_no_critic"),
        ("wordle_withclue", "high_frequency_words_clue_no_critic"),
        ("wordle_withcritic", "high_frequency_words_clue_with_critic"),
    ],
    "hard": [
        ("adventuregame", "home_deliver_three_basic_hard"),
        ("adventuregame", "home_deliver_three_planning_hard"),
        ("adventuregame", "home_deliver_three_basic_hard_invlimittwo"),
        ("adventuregame", "home_deliver_three_planning_hard_invlimittwo"),
        ("guesswhat", "Level_3"),
        ("guesswhat", "Abs_Level_3"),
        ("matchit_ascii", "different_grid"),
        ("reference_game", "random_grids"),
        ("taboo", "low_en"),
        ("textmapworld", "large"),
        ("textmapworld", "medium_cycle"),
        ("textmapworld", "large_cycle"),
        ("textmap_graphreasoning", "large"),
        ("textmap_specificroom", "far"),
        ("wordle_withclue", "medium_frequency_words_clue_no_critic"),
        ("wordle_withcritic", "medium_frequency_words_clue_with_critic"),
    ],
}
